# Github Syntax Reference 
# 1. https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows
# 2. https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
# 3. https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

name: Django    # workflow name

on:
  push:
    branches:   # similar to "only" in GitLab
      - master

jobs:
  build:
    runs-on: ubuntu-latest    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"    # similar to "script" in GitLab
  
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test step"

  integration:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo "This is an integration step"
      - run: exit 1

  prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a deploy step"

  artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "artifact job ouput" > output.txt
      - name: upload result for artifact job
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: output.txt
  
  
